version: '3.9'

services:
  postgres-dev:
    container_name: postgres-dev
    image: bookabite-postgres-dev:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_NAME_DEV}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bookabite-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_DEV}"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  pgdata_dev:

networks:
  bookabite-network:
    external: true
