version: '3.9'

services:
  backend:
    container_name: restaurant-backend
    image: bookabite-restaurant-back-dev:latest
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER_DEV}:${POSTGRES_PASSWORD_DEV}@${POSTGRES_HOST_DEV}:${POSTGRES_PORT_DEV}/${POSTGRES_NAME_DEV}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - bookabite-network

networks:
  bookabite-network:
    external: true
