version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: restaurant-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER_DEV}:${POSTGRES_PASSWORD_DEV}@${POSTGRES_HOST_DEV}:${POSTGRES_PORT_DEV}/${POSTGRES_NAME_DEV}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - bookabite_dev

  bookabite_dev:
    image: postgres:latest
    container_name: bookabite-dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_NAME_DEV}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_dev:
