version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER_DEV}:${DB_PASSWORD_DEV}@${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - bookabite_dev

  bookabite_dev:
    image: postgres:latest
    container_name: bookabite-postgresql-dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER_DEV=${DB_USER_DEV}
      - POSTGRES_PASSWORD_DEV=${DB_PASSWORD_DEV}
      - POSTGRES_DB_DEV=${DB_NAME_DEV}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_dev:
