name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME_DEV }}
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Wait for PostgreSQL to be ready
#      run: |
#        echo "Waiting for PostgreSQL to be ready..."
#        count=0
#        max_retries=60
#        while ! pg_isready -h localhost -p 5432 &>/dev/null; do
#          ((count++))
#          echo "Waiting for PostgreSQL... attempt $count"
#          if [ $count -gt $max_retries ]; then
#            echo "PostgreSQL did not respond within $max_retries seconds."
#            exit 1
#          fi
#          sleep 1
#        done
#        echo "PostgreSQL is ready"

#    - name: Run migrations and tests
#      env:
#        DB_ENGINE: ${{ secrets.DB_ENGINE }}
#        DB_NAME: ${{ secrets.DB_NAME_DEV }}
#        DB_USER: ${{ secrets.DB_USER }}
#        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        DB_HOST: ${{ secrets.DB_HOST }}
#        DB_PORT: ${{ secrets.DB_PORT }}
#      run: |
#        python manage.py migrate
#        python manage.py test

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t samuelamt/restaurant-back-dev:latest .
        docker tag samuelamt/restaurant-back-dev:latest samuelamt/restaurant-back-dev:latest
        docker push samuelamt/restaurant-back-dev:latest
